timeout-decoder : 10
decoder:
   model: /opt/tri3a/final.mdl
   lda-mat: /opt/tri3a/final.mat
   word-syms: /opt/tri3a/words.txt
   fst: /opt/tri3a/HCLG.fst
   silence-phones: "1:2:3:4:5"
out-dir: tmp

use-vad: False
silence-timeout: 60

# Just a sample post-processor that appends "." to the hypothesis
post-processor: perl -npe 'BEGIN {use IO::Handle; STDOUT->autoflush(1);} s/(.*)/\1./;'
logging:
    version : 1
    disable_existing_loggers: False
    formatters:
        simpleFormater:
            format: '%(asctime)s - %(levelname)7s: %(name)10s: %(message)s'
            datefmt: '%Y-%m-%d %H:%M:%S'
    handlers:
        console:
            class: logging.StreamHandler
            formatter: simpleFormater
            level: DEBUG
    root:
        level: DEBUG
        handlers: [console]